### ISSUE TITLE
Remove period at end of summary

### ISSUE THREAD

**Issue by razzeee** [flathub/org.blackcoin.blackcoin-more#8]
https://github.com/flathub/org.blackcoin.blackcoin-more/blob/master/org.blackcoin.blackcoin-more.metainfo.xml#L7

**Comment by BlackcoinDev** [comment]
> https://github.com/flathub/org.blackcoin.blackcoin-more/blob/master/org.blackcoin.blackcoin-more.metainfo.xml#L7

please let me know if you have more suggustions. You may also open an PR on our repo
https://github.com/CoinBlack/org.blackcoin.blackcoin-more
